version: '3.3'
services:

  db:
    image: postgres:16-alpine
    # ports:
    #   - 127.0.0.1:15432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      # - /etc/passwd:/etc/passwd:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:?Please configure in .env}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  odoo:
    build: ./build/odoo
    command: start
    ports:
      - 127.0.0.1:${ODOO_PORT:-8069}:8069
    volumes:
      - ./volumes/odoo/addons:/opt/odoo/additional_addons
      - ./volumes/odoo/filestore:/opt/odoo/data/filestore
      - ./volumes/odoo/sessions:/opt/odoo/data/sessions
      - ./volumes/odoo/scripts:/opt/scripts
      - ~/.ssh:/opt/odoo/ssh:ro
    environment:
      - ODOO_ADMIN_PASSWD=${ODOO_ADMIN_PASSWD:?Please configure in .env}
      - ODOO_DB_USER=${ODOO_DB_USER:?Please configure in .env}
      - ODOO_DB_PASSWORD=${ODOO_DB_PASSWORD:?Please configure in .env}
    depends_on:
      db:
        condition: service_healthy
